### ISSUE TITLE
Push rejected, failed to detect set buildpack git://github.com/CHH/heroku-buildpack-php

### ISSUE THREAD

**Issue by kovacsa91** [seatgeek/build-artifacts#3]
I got an error during `git push heroku master` process.

> remote: Building source:
> remote:
> remote: -----> Fetching set buildpack git://github.com/CHH/heroku-buildpack-php... done
> remote:
> remote:  !     Push rejected, failed to detect set buildpack git://github.com/CHH/heroku-buildpack-php
> remote: More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
> remote:
> remote: Verifying deploy....
> remote:
> remote: !       Push rejected to

**Comment by josegonzalez** [comment]
That buildpack is quite old, maybe worth seeing if this works in the latest php buildpack? I originally used it because the php buildpack at the time wasn't so great and didn't have composer support I think.

**Comment by kovacsa91** [comment]
I have resolved this error with using another buildpack, but after successful pushing have got an error in browser:

> Forbidden
> You don't have permission to access / on this server.

**Comment by josegonzalez** [comment]
What buildpack did you switch to?

**Comment by kovacsa91** [comment]
To this: https://github.com/heroku/heroku-buildpack-php

**Comment by josegonzalez** [comment]
Gotcha.

I can try taking a look at this later today (working on some internal infra atm). Is that fine with you?

**Comment by kovacsa91** [comment]
Yes, thanks in advance!

**Comment by kovacsa91** [comment]
Have you found maybe about this?

**Comment by josegonzalez** [comment]
Closing in favor of #4.
